import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=await readFile('worker/page.html','utf8');
const script=html.match(/<script>([\s\S]*)<\/script>/)[1];
new vm.Script(script);
const c=vm.createContext({Date,Number,JSON,Error});
const extract=(a,b)=>script.slice(script.indexOf(a),script.indexOf(b));
vm.runInContext(extract('function percentile','function filterRows')+extract('function csvParse','function importText'),c);
const stats=vm.runInContext('statistics([{price:10,quantity:1},{price:20,quantity:9}])',c);
assert.equal(stats.avg,19);assert.equal(stats.min,10);assert.equal(stats.max,20);assert.equal(stats.median,15);assert.equal(stats.qty,10);
assert.equal(vm.runInContext('statistics([]).avg',c),null);
assert.equal(vm.runInContext('percentile([10,20,30,40],.25)',c),17.5);
assert.equal(vm.runInContext(`csvParse('name,variant\\r\\n"a,b","x""y"')[0].name`,c),'a,b');
assert.throws(()=>vm.runInContext(`csvParse('name\\n"unfinished')`,c));
const good={name:'鋼錠',variant:'',type:'item',currency:'魔幣',price:20,quantity:5,server:'S1',date:'2026-10-04T10:00:00+08:00',status:'sold'};
c.row=good;assert.equal(vm.runInContext('validate([row])[0].quantity',c),5);
for (const bad of [{quantity:0},{quantity:1.5},{price:-1},{currency:'USD'},{date:'2026-10-04T10:00:00'},{date:'2099-10-04T10:00:00+08:00'},{server:'S9'}]){c.row={...good,...bad};assert.throws(()=>vm.runInContext('validate([row])',c));}
const {default:worker}=await import('../worker/index.js');
assert.equal((await worker.fetch(new Request('https://test/'))).status,200);
const originalFetch=globalThis.fetch;
globalThis.fetch=async url=>Response.json({stalls:new URL(url).searchParams.get('page')==='1'?[{cdkey:'seller',name:'測試攤位',coords:'東 10 南 20'}]:[],itemsByCd:new URL(url).searchParams.get('page')==='1'?{seller:[{ITEM_TRUENAME:'鋼錠',price:200,pricetype:0,ITEM_REMAIN:20}]}:{},petsByCd:{}});
const apiResponse=await worker.fetch(new Request('https://test/api/search?q=鋼錠&server=S1'));
assert.equal(apiResponse.status,200);
const payload=await apiResponse.json();assert.equal(payload.rows[0].price,200);assert.equal(payload.rows[0].quantity,20);assert.equal(payload.rows[0].priceBasis,'official');assert.equal(payload.rows[0].currency,'魔幣');assert.equal(payload.rows[0].server,'S1');
globalThis.fetch=async()=>new Response('<html>unavailable</html>');
assert.equal((await worker.fetch(new Request('https://test/api/search?q=另一個名字&server=S1'))).status,502);
globalThis.fetch=originalFetch;
assert.equal((await worker.fetch(new Request('https://test/api/search'))).status,400);
assert.equal((await worker.fetch(new Request('https://test/missing'))).status,404);
console.log('Price statistics, CSV parsing, import validation, browser JS syntax and HTTP routes passed.');
