import assert from 'node:assert/strict';
import {planShopping,mergeNeeds,readPosition} from '../worker/planner.js';
import {normalizeHistory} from '../worker/backend.js';
assert.deepEqual(readPosition('法蘭城 [東:180 南:56]'),{map:'法蘭城',x:180,y:56});
const base={status:'listing',type:'item',currency:'魔幣',server:'S1'};
const stock=[{...base,name:'劍',price:100,quantity:2,stall:'A',coords:'法蘭城 [東:2 南:0]'},{...base,name:'弓',price:100,quantity:3,stall:'A',coords:'法蘭城 [東:2 南:0]'},{...base,name:'劍',price:50,quantity:1,stall:'B',coords:'法蘭城 [東:10 南:0]'},{...base,name:'弓',price:50,quantity:1,stall:'B',coords:'法蘭城 [東:10 南:0]'},{...base,name:'劍',price:50,quantity:1,stall:'C',coords:'法蘭城 [東:20 南:0]'},{...base,name:'弓',price:50,quantity:2,stall:'C',coords:'法蘭城 [東:20 南:0]'}];
const batch=[{name:'劍',quantity:2},{name:'弓',quantity:3}],opts={x:0,y:0,map:'法蘭城',server:'S1',currency:'魔幣',unitMode:'unit',strategy:'distance'};
const near=planShopping(batch,stock,opts);assert(near.complete);assert.equal(near.distance,2);assert.equal(near.route.length,1);assert.equal(near.cost,500);
const cheap=planShopping(batch,stock,{...opts,strategy:'price'});assert.equal(cheap.cost,250);assert.equal(cheap.route.length,2);assert.equal(cheap.distance,20);
const stop=planShopping(batch,stock,{...opts,strategy:'stops'});assert.equal(stop.route.length,1);
const back=planShopping(batch,stock,{...opts,returnToStart:true});assert.equal(back.distance,4);
const insufficient=planShopping([{name:'劍',quantity:10}],stock,opts);assert(!insufficient.complete);assert.equal(insufficient.missing[0].quantity,6);
assert.equal(mergeNeeds([{name:'劍',quantity:3,owned:2,times:2},{name:'劍',quantity:2,owned:2}])[0].missing,6);
const mapMismatch=planShopping(batch,stock.map(r=>({...r,coords:'伊爾村 [東:2 南:0]'})),opts);assert(!mapMismatch.complete);assert.equal(mapMismatch.route.length,0);
const serverMismatch=planShopping(batch,stock,{...opts,server:'S2'});assert(!serverMismatch.complete);
const allOwned=planShopping([{name:'劍',quantity:2,owned:2}],stock,opts);assert(allOwned.complete);assert.equal(allOwned.distance,0);
assert.throws(()=>mergeNeeds([{name:'劍',quantity:0}]));assert.throws(()=>planShopping(batch,stock,{...opts,x:NaN}));
const h=normalizeHistory([{id:1,item_name:'[火焰鼠]',qty:1,unit_gross_price:2300,ts:1791214355,pricetype:0,buff:'購買寵物：[火焰鼠]'}]);assert.equal(h[0].name,'火焰鼠');assert.equal(h[0].type,'pet');assert.equal(h[0].price,2300);
assert.deepEqual(normalizeHistory([{item_name:'[劍]',qty:0,unit_gross_price:10,ts:100,pricetype:0}]),[]);
console.log('Multi-item stock allocation, quantity merge, shared inventory, route optimization, map/server separation and gross transaction price passed.');
